<?php
/**
 * PerOperationLimitPeriodic1Response
 *
 * PHP version 5
 *
 * @category Class
 * @package  TmApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Megaputer Text Mining API
 *
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TmApi\Model;

use \ArrayAccess;
use \TmApi\ObjectSerializer;

/**
 * PerOperationLimitPeriodic1Response Class Doc Comment
 *
 * @category Class
 * @package  TmApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PerOperationLimitPeriodic1Response implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PerOperationLimitPeriodic1Response';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'ntu_period1' => 'string',
        'ntu_in_period1_limit' => 'int',
        'ntu_in_period1_tokens' => 'int',
        'ntu_in_period1_keywords' => 'int',
        'ntu_in_period1_entities' => 'int',
        'ntu_in_period1_languages' => 'int',
        'ntu_in_period1_sentiments' => 'int',
        'ntu_in_period1_facts' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'ntu_period1' => null,
        'ntu_in_period1_limit' => 'int32',
        'ntu_in_period1_tokens' => 'int32',
        'ntu_in_period1_keywords' => 'int32',
        'ntu_in_period1_entities' => 'int32',
        'ntu_in_period1_languages' => 'int32',
        'ntu_in_period1_sentiments' => 'int32',
        'ntu_in_period1_facts' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ntu_period1' => 'NTUPeriod1',
        'ntu_in_period1_limit' => 'NTUInPeriod1Limit',
        'ntu_in_period1_tokens' => 'NTUInPeriod1Tokens',
        'ntu_in_period1_keywords' => 'NTUInPeriod1Keywords',
        'ntu_in_period1_entities' => 'NTUInPeriod1Entities',
        'ntu_in_period1_languages' => 'NTUInPeriod1Languages',
        'ntu_in_period1_sentiments' => 'NTUInPeriod1Sentiments',
        'ntu_in_period1_facts' => 'NTUInPeriod1Facts'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ntu_period1' => 'setNtuPeriod1',
        'ntu_in_period1_limit' => 'setNtuInPeriod1Limit',
        'ntu_in_period1_tokens' => 'setNtuInPeriod1Tokens',
        'ntu_in_period1_keywords' => 'setNtuInPeriod1Keywords',
        'ntu_in_period1_entities' => 'setNtuInPeriod1Entities',
        'ntu_in_period1_languages' => 'setNtuInPeriod1Languages',
        'ntu_in_period1_sentiments' => 'setNtuInPeriod1Sentiments',
        'ntu_in_period1_facts' => 'setNtuInPeriod1Facts'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ntu_period1' => 'getNtuPeriod1',
        'ntu_in_period1_limit' => 'getNtuInPeriod1Limit',
        'ntu_in_period1_tokens' => 'getNtuInPeriod1Tokens',
        'ntu_in_period1_keywords' => 'getNtuInPeriod1Keywords',
        'ntu_in_period1_entities' => 'getNtuInPeriod1Entities',
        'ntu_in_period1_languages' => 'getNtuInPeriod1Languages',
        'ntu_in_period1_sentiments' => 'getNtuInPeriod1Sentiments',
        'ntu_in_period1_facts' => 'getNtuInPeriod1Facts'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const NTU_PERIOD1_SECOND = 'Second';
    const NTU_PERIOD1_MINUTE = 'Minute';
    const NTU_PERIOD1_HOUR = 'Hour';
    const NTU_PERIOD1_DAY = 'Day';
    const NTU_PERIOD1_MONTH = 'Month';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getNtuPeriod1AllowableValues()
    {
        return [
            self::NTU_PERIOD1_SECOND,
            self::NTU_PERIOD1_MINUTE,
            self::NTU_PERIOD1_HOUR,
            self::NTU_PERIOD1_DAY,
            self::NTU_PERIOD1_MONTH,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ntu_period1'] = isset($data['ntu_period1']) ? $data['ntu_period1'] : null;
        $this->container['ntu_in_period1_limit'] = isset($data['ntu_in_period1_limit']) ? $data['ntu_in_period1_limit'] : null;
        $this->container['ntu_in_period1_tokens'] = isset($data['ntu_in_period1_tokens']) ? $data['ntu_in_period1_tokens'] : null;
        $this->container['ntu_in_period1_keywords'] = isset($data['ntu_in_period1_keywords']) ? $data['ntu_in_period1_keywords'] : null;
        $this->container['ntu_in_period1_entities'] = isset($data['ntu_in_period1_entities']) ? $data['ntu_in_period1_entities'] : null;
        $this->container['ntu_in_period1_languages'] = isset($data['ntu_in_period1_languages']) ? $data['ntu_in_period1_languages'] : null;
        $this->container['ntu_in_period1_sentiments'] = isset($data['ntu_in_period1_sentiments']) ? $data['ntu_in_period1_sentiments'] : null;
        $this->container['ntu_in_period1_facts'] = isset($data['ntu_in_period1_facts']) ? $data['ntu_in_period1_facts'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getNtuPeriod1AllowableValues();
        if (!is_null($this->container['ntu_period1']) && !in_array($this->container['ntu_period1'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'ntu_period1', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ntu_period1
     *
     * @return string|null
     */
    public function getNtuPeriod1()
    {
        return $this->container['ntu_period1'];
    }

    /**
     * Sets ntu_period1
     *
     * @param string|null $ntu_period1 A period when limitations apply
     *
     * @return $this
     */
    public function setNtuPeriod1($ntu_period1)
    {
        $allowedValues = $this->getNtuPeriod1AllowableValues();
        if (!is_null($ntu_period1) && !in_array($ntu_period1, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'ntu_period1', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['ntu_period1'] = $ntu_period1;

        return $this;
    }

    /**
     * Gets ntu_in_period1_limit
     *
     * @return int|null
     */
    public function getNtuInPeriod1Limit()
    {
        return $this->container['ntu_in_period1_limit'];
    }

    /**
     * Sets ntu_in_period1_limit
     *
     * @param int|null $ntu_in_period1_limit A maximum number of requests in the specified period
     *
     * @return $this
     */
    public function setNtuInPeriod1Limit($ntu_in_period1_limit)
    {
        $this->container['ntu_in_period1_limit'] = $ntu_in_period1_limit;

        return $this;
    }

    /**
     * Gets ntu_in_period1_tokens
     *
     * @return int|null
     */
    public function getNtuInPeriod1Tokens()
    {
        return $this->container['ntu_in_period1_tokens'];
    }

    /**
     * Sets ntu_in_period1_tokens
     *
     * @param int|null $ntu_in_period1_tokens A number of requests that have already been processed for operation Text parsing
     *
     * @return $this
     */
    public function setNtuInPeriod1Tokens($ntu_in_period1_tokens)
    {
        $this->container['ntu_in_period1_tokens'] = $ntu_in_period1_tokens;

        return $this;
    }

    /**
     * Gets ntu_in_period1_keywords
     *
     * @return int|null
     */
    public function getNtuInPeriod1Keywords()
    {
        return $this->container['ntu_in_period1_keywords'];
    }

    /**
     * Sets ntu_in_period1_keywords
     *
     * @param int|null $ntu_in_period1_keywords A number of requests that have already been processed for operation Keywords extraction
     *
     * @return $this
     */
    public function setNtuInPeriod1Keywords($ntu_in_period1_keywords)
    {
        $this->container['ntu_in_period1_keywords'] = $ntu_in_period1_keywords;

        return $this;
    }

    /**
     * Gets ntu_in_period1_entities
     *
     * @return int|null
     */
    public function getNtuInPeriod1Entities()
    {
        return $this->container['ntu_in_period1_entities'];
    }

    /**
     * Sets ntu_in_period1_entities
     *
     * @param int|null $ntu_in_period1_entities A number of requests that have already been processed for operation Entities extraction
     *
     * @return $this
     */
    public function setNtuInPeriod1Entities($ntu_in_period1_entities)
    {
        $this->container['ntu_in_period1_entities'] = $ntu_in_period1_entities;

        return $this;
    }

    /**
     * Gets ntu_in_period1_languages
     *
     * @return int|null
     */
    public function getNtuInPeriod1Languages()
    {
        return $this->container['ntu_in_period1_languages'];
    }

    /**
     * Sets ntu_in_period1_languages
     *
     * @param int|null $ntu_in_period1_languages A number of requests that have already been processed for operation Language detection
     *
     * @return $this
     */
    public function setNtuInPeriod1Languages($ntu_in_period1_languages)
    {
        $this->container['ntu_in_period1_languages'] = $ntu_in_period1_languages;

        return $this;
    }

    /**
     * Gets ntu_in_period1_sentiments
     *
     * @return int|null
     */
    public function getNtuInPeriod1Sentiments()
    {
        return $this->container['ntu_in_period1_sentiments'];
    }

    /**
     * Sets ntu_in_period1_sentiments
     *
     * @param int|null $ntu_in_period1_sentiments A number of requests that have already been processed for operation Sentiments analysis
     *
     * @return $this
     */
    public function setNtuInPeriod1Sentiments($ntu_in_period1_sentiments)
    {
        $this->container['ntu_in_period1_sentiments'] = $ntu_in_period1_sentiments;

        return $this;
    }

    /**
     * Gets ntu_in_period1_facts
     *
     * @return int|null
     */
    public function getNtuInPeriod1Facts()
    {
        return $this->container['ntu_in_period1_facts'];
    }

    /**
     * Sets ntu_in_period1_facts
     *
     * @param int|null $ntu_in_period1_facts A number of requests that have already been processed for operation Facts extraction
     *
     * @return $this
     */
    public function setNtuInPeriod1Facts($ntu_in_period1_facts)
    {
        $this->container['ntu_in_period1_facts'] = $ntu_in_period1_facts;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


